-- Head of Nefarian has duplicates for Horde and Alliance
-- Allowing duplicates results in people picking the wrong one for wishlists or having to list two
DELETE FROM `items` WHERE `item_id` = 19003;
-- 19003 = Alliance
-- 19002 = Horde

-- Head of Onyxia has duplicates for Horde and Alliance
-- Allowing duplicates results in people picking the wrong one for wishlists or having to list two
DELETE FROM `items` WHERE `item_id` = 18423;
-- 18423 = Alliance
-- 18422 = Horde

-- Without these, there's no way to distinguish them.
UPDATE `items` SET `name` = "Atiesh, Greatstaff of the Guardian (mage)"    WHERE `item_id` = 22589;
UPDATE `items` SET `name` = "Atiesh, Greatstaff of the Guardian (priest)"  WHERE `item_id` = 22631;
UPDATE `items` SET `name` = "Atiesh, Greatstaff of the Guardian (druid)"   WHERE `item_id` = 22632;
UPDATE `items` SET `name` = "Atiesh, Greatstaff of the Guardian (warlock)" WHERE `item_id` = 22630;

UPDATE `items` SET `name` = "Bindings of the Windseeker (left)"  WHERE `item_id` = 18563;
UPDATE `items` SET `name` = "Bindings of the Windseeker (right)" WHERE `item_id` = 18564;

UPDATE `items` SET `description` = "Good luck." WHERE `item_id` = 17782; -- Talisman of Binding Shard

-- ZG loot weights
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19724; -- primal-hakkari-aegis
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19717; -- primal-hakkari-armsplint
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19716; -- primal-hakkari-bindings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19719; -- primal-hakkari-girdle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22637; -- primal-hakkari-idol
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19723; -- primal-hakkari-kossack
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19720; -- primal-hakkari-sash
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19721; -- primal-hakkari-shawl
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19718; -- primal-hakkari-stanchion
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19722; -- primal-hakkari-tabard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20263; -- gurubashi-helm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19908; -- sceptre-of-smiting
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20259; -- shadow-panther-hide-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20261; -- shadow-panther-hide-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20258; -- zulian-ceremonial-staff
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19921; -- zulian-hacker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22721; -- band-of-servitude
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22716; -- belt-of-untapped-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22718; -- blooddrenched-mask
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22711; -- cloak-of-the-hakkari-worshipers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22715; -- gloves-of-the-tormented
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22712; -- might-of-the-tribe
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22714; -- sacrificial-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22722; -- seal-of-the-gurubashi-berserker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22720; -- zulian-headdress
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22713; -- zulian-scepter-of-rites
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19928; -- animists-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19918; -- jekliks-crusher
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19923; -- jekliks-opaline-talisman
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20265; -- peacekeeper-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19920; -- primalists-band
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20262; -- seafury-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19915; -- zulian-defender
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19906; -- blooddrenched-footpads
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19903; -- fang-of-venoxis
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19904; -- runed-bloodstained-hauberk
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19905; -- zanzils-band
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19900; -- zulian-stone-axe
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19907; -- zulian-tigerhide-cloak
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19925; -- band-of-jin
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19919; -- bloodstained-greaves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20032; -- flowing-ritual-robes
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19930; -- marlis-eye
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19927; -- marlis-touch
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19871; -- talisman-of-protection
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19877; -- animists-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19869; -- blooddrenched-grips
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19867; -- bloodlords-defender
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19878; -- bloodsoaked-pauldrons
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19895; -- bloodtinged-kilt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19870; -- hakkari-loa-cloak
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19874; -- halberd-of-smiting
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20038; -- mandokirs-sting
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19873; -- overlords-crimson-band
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19863; -- primalists-seal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19872; -- swift-razzashi-raptor
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19893; -- zanzils-seal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19866; -- warblade-of-the-hakkari
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19968; -- fiery-retributer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19939; -- grileks-blood
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19962; -- grileks-carver
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19961; -- grileks-grinder
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19942; -- hazzarahs-dream-thread
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19993; -- hoodoo-hunting-bow
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19963; -- pitchfork-of-madness
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19940; -- renatakis-tooth
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19964; -- renatakis-soul-conduit
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19967; -- thoughtblighter
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19941; -- wushoolays-mane
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19965; -- wushoolays-poker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19897; -- betrayers-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20266; -- peacekeeper-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19899; -- ritualistic-legguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20260; -- seafury-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19898; -- seal-of-jin
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19902; -- swift-zulian-tiger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19896; -- thekals-grasp
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19901; -- zulian-slicer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19945; -- forors-eyepatch
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19947; -- nat-pagles-broken-reel
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19944; -- nat-pagles-fish-terminator
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19946; -- tigules-harpoon
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22739; -- tome-of-polymorph-turtle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19910; -- arlokks-grasp
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19922; -- arlokks-hoodoo-stick
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19913; -- bloodsoaked-greaves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19912; -- overlords-onyx-band
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19914; -- panther-hide-sack
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19909; -- will-of-arlokk
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19892; -- animists-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19889; -- blooddrenched-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19894; -- bloodsoaked-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19875; -- bloodstained-coif
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19887; -- bloodstained-legplates
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19929; -- bloodtinged-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19891; -- jindos-bag-of-whammies
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19885; -- jindos-evil-eye
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19890; -- jindos-hexxer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19884; -- jindos-judgement
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19888; -- overlords-embrace
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19886; -- the-hexxers-cover
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19862; -- aegis-of-the-blood-god
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19852; -- ancient-hakkari-manslayer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19864; -- bloodcaller
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19855; -- bloodsoaked-legplates
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19857; -- cloak-of-consumption
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19859; -- fang-of-the-faceless
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19853; -- gurubashi-dwarf-destroyer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19802; -- heart-of-hakkar
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20264; -- peacekeeper-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20257; -- seafury-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19876; -- soul-corrupters-necklace
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19856; -- the-eye-of-hakkar
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19861; -- touch-of-chaos
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19865; -- warblade-of-the-hakkari
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19854; -- zinrokh-destroyer-of-worlds

-- AQ20 loot weights
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20734; -- formula-enchant-cloak-stealth
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20728; -- formula-enchant-gloves-frost-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20730; -- formula-enchant-gloves-healing-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20731; -- formula-enchant-gloves-superior-agility
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20888; -- qiraji-ceremonial-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20884; -- qiraji-magisterial-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20885; -- qiraji-martial-drape
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20890; -- qiraji-ornate-hilt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20889; -- qiraji-regal-drape
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20886; -- qiraji-spiked-hilt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21801; -- antenna-of-invigoration
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21804; -- coif-of-elemental-fury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21809; -- fury-of-the-forgotten-swarm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21806; -- gavel-of-qiraji-authority
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21803; -- helm-of-the-holy-avenger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21800; -- silithid-husked-launcher
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21802; -- the-lost-kris-of-zedd
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21810; -- treads-of-the-wandering-nomad
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21500; -- belt-of-the-inquisition
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21503; -- belt-of-the-sand-reaver
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21498; -- qiraji-sacrificial-dagger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21502; -- sand-reaver-wristguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21501; -- toughened-silithid-hide-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21499; -- vestments-of-the-shifting-sands
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21497; -- boots-of-the-qiraji-general
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21493; -- boots-of-the-vanguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21496; -- bracers-of-qiraji-command
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21495; -- legplates-of-the-qiraji-command
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21492; -- manslayer-of-the-qiraji
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21494; -- southwinds-grasp
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21474; -- chitinous-shoulderguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21470; -- cloak-of-the-savior
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21472; -- dustwind-turban
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21473; -- eye-of-moam
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21469; -- gauntlets-of-southwind
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21479; -- gauntlets-of-the-immovable
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21475; -- legplates-of-the-destroyer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21468; -- mantle-of-maznadir
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21476; -- obsidian-scaled-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22220; -- plans-black-grasp-of-the-destroyer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21477; -- ring-of-fury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21455; -- southwind-helm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21471; -- talon-of-furious-concentration
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21467; -- thick-silithid-chestguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21485; -- burus-skull-fragment
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21488; -- fetish-of-chitinous-spikes
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21486; -- gloves-of-the-swarm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21489; -- quicksand-waders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21491; -- scaled-bracers-of-the-gorger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21490; -- slime-kickers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21487; -- slimy-scaled-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21479; -- gauntlets-of-the-immovable
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21481; -- boots-of-the-desert-protector
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21482; -- boots-of-the-fiery-sands
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21478; -- bow-of-taut-sinew
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21484; -- helm-of-regrowth
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21483; -- ring-of-the-desert-winds
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21480; -- scaled-silithid-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21466; -- stinger-of-ayamiss
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21457; -- bracers-of-brutality
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21459; -- crossbow-of-imminent-doom
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21458; -- gauntlets-of-new-life
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21462; -- gloves-of-dark-wisdom
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21220; -- head-of-ossirian-the-unscarred
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21460; -- helm-of-domination
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21461; -- leggings-of-the-black-blizzard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21453; -- mantle-of-the-horusath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21463; -- ossirians-binding
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21454; -- runic-stone-shoulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21715; -- sand-polished-hammer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21456; -- sandstorm-cloak
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21464; -- shackles-of-the-unscarred
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21452; -- staff-of-the-ruins

-- MC loot weights
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18260; -- formula-enchant-weapon-healing-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18259; -- formula-enchant-weapon-spell-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18252; -- pattern-core-armor-kit
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21371; -- pattern-core-felcloth-bag
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18265; -- pattern-flarecore-wraps
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18264; -- plans-elemental-sharpening-stone
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18257; -- recipe-major-rejuvenation-potion
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18290; -- schematic-biznicks-247x128-accurascope
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18292; -- schematic-core-marksman-rifle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18291; -- schematic-force-reactive-disk
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16802; -- arcanist-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16799; -- arcanist-bindings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16864; -- belt-of-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16861; -- bracers-of-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16828; -- cenarion-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16830; -- cenarion-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16838; -- earthfury-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16840; -- earthfury-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16806; -- felheart-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16804; -- felheart-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16851; -- giantstalkers-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16850; -- giantstalkers-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16817; -- girdle-of-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16858; -- lawbringer-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16857; -- lawbringer-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16827; -- nightslayer-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16825; -- nightslayer-bracelets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16819; -- vambraces-of-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18823; -- aged-core-leather-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17077; -- crimson-shocker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18829; -- deep-earth-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19142; -- fire-runed-grimoire
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19143; -- flameguard-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18861; -- flamewaker-legplates
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18879; -- heavy-dark-iron-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18824; -- magma-tempered-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19136; -- mana-igniting-cord
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18872; -- manastorm-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18822; -- obsidian-edged-blade
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18821; -- quick-strike-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19147; -- ring-of-spell-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19145; -- robe-of-volatile-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19144; -- sabatons-of-the-flamewalker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18875; -- salamander-scale-pants
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18878; -- sorcerous-dagger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18820; -- talisman-of-ephemeral-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19146; -- wristguards-of-stability
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16800; -- arcanist-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16829; -- cenarion-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17109; -- choker-of-enlightenment
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16837; -- earthfury-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16805; -- felheart-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16863; -- gauntlets-of-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16859; -- lawbringer-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16665; -- tome-of-tranquilizing-shot
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16796; -- arcanist-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16835; -- cenarion-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16843; -- earthfury-legguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17073; -- earthshaker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18203; -- eskhandars-right-claw
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16810; -- felheart-pants
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16847; -- giantstalkers-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16855; -- lawbringer-legplates
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16867; -- legplates-of-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17065; -- medallion-of-steadfast-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16822; -- nightslayer-pants
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16814; -- pants-of-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17069; -- strikers-mark
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16839; -- earthfury-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16849; -- giantstalkers-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16812; -- gloves-of-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16860; -- lawbringer-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16826; -- nightslayer-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16862; -- sabatons-of-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16795; -- arcanist-crown
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17105; -- aurastone-hammer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18564; -- bindings-of-the-windseeker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18832; -- brutality-blade
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16834; -- cenarion-helm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16813; -- circlet-of-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17066; -- drillborer-disk
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16842; -- earthfury-helmet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16808; -- felheart-horns
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16846; -- giantstalkers-helmet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17071; -- gutgore-ripper
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16866; -- helm-of-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16854; -- lawbringer-helm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16821; -- nightslayer-cover
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16801; -- arcanist-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16811; -- boots-of-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16831; -- cenarion-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16803; -- felheart-slippers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16852; -- giantstalkers-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16824; -- nightslayer-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16797; -- arcanist-mantle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18563; -- bindings-of-the-windseeker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16836; -- cenarion-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16844; -- earthfury-epaulets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16807; -- felheart-shoulder-pads
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16856; -- lawbringer-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17110; -- seal-of-the-archmagus
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17782; -- talisman-of-binding-shard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16798; -- arcanist-robes
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17103; -- azuresong-mageblade
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17072; -- blastershot-launcher
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16865; -- breastplate-of-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16833; -- cenarion-vestments
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16841; -- earthfury-vestments
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16809; -- felheart-robes
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16845; -- giantstalkers-breastplate
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16853; -- lawbringer-chestguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16820; -- nightslayer-chestpiece
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16820; -- nightslayer-chestpiece
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16815; -- robes-of-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18842; -- staff-of-dominance
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16848; -- giantstalkers-epaulets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16816; -- mantle-of-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16823; -- nightslayer-shoulder-pads
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16868; -- pauldrons-of-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17074; -- shadowstrike
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18703; -- ancient-petrified-leaf
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19140; -- cauterizing-band
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18806; -- core-forged-greaves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18805; -- core-hound-tooth
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18803; -- finkles-lava-dredger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19139; -- fireguard-shoulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18811; -- fireproof-cloak
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18808; -- gloves-of-the-hypnotic-flame
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18809; -- sash-of-whispered-secrets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18646; -- the-eye-of-divinity
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18810; -- wild-growth-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18812; -- wristguards-of-true-flight
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17063; -- band-of-accuria
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19138; -- band-of-sulfuras
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16909; -- bloodfang-pants
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17076; -- bonereavers-edge
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18814; -- choker-of-the-fire-lord
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17102; -- cloak-of-the-shrouded-mists
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18817; -- crown-of-destruction
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17107; -- dragons-blood-cape
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16938; -- dragonstalkers-legguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18815; -- essence-of-the-pure-flame
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17204; -- eye-of-sulfuras
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16954; -- judgement-legplates
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16922; -- leggings-of-transcendence
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16946; -- legplates-of-ten-storms
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16962; -- legplates-of-wrath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17106; -- malistars-defender
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16930; -- nemesis-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16915; -- netherwind-pants
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19137; -- onslaught-girdle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18816; -- perditions-blade
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17082; -- shard-of-the-flame
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17104; -- spinal-reaper
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16901; -- stormrage-legguards

-- Onyxia loot weights
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17067; -- ancient-cornerstone-grimoire
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16908; -- bloodfang-hood
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17068; -- deathbringer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16939; -- dragonstalkers-helm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18205; -- eskhandars-collar
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16921; -- halo-of-transcendence
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18422; -- head-of-onyxia
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16963; -- helm-of-wrath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16947; -- helmet-of-ten-storms
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16955; -- judgement-crown
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18705; -- mature-black-dragon-sinew
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16929; -- nemesis-skullcap
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16914; -- netherwind-crown
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17966; -- onyxia-hide-backpack
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 18813; -- ring-of-binding
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17078; -- sapphiron-drape
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17064; -- shard-of-the-scale
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16900; -- stormrage-cover
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17075; -- viskag-the-bloodletter

-- BWL loot weights
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19434; -- band-of-dark-dominion
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19437; -- boots-of-pure-thought
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19436; -- cloak-of-draconic-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19362; -- dooms-edge
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19354; -- draconic-avenger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19358; -- draconic-maul
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19435; -- essence-gatherer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19439; -- interlaced-shadow-jerkin
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19438; -- ringos-blizzard-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19336; -- arcane-infused-gem
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16926; -- bindings-of-transcendence
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16911; -- bloodfang-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16959; -- bracelets-of-wrath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16943; -- bracers-of-ten-storms
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16935; -- dragonstalkers-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19369; -- gloves-of-rapid-evolution
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16951; -- judgement-bindings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19370; -- mantle-of-the-blackwing-cabal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16934; -- nemesis-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16918; -- netherwind-bindings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19335; -- spineshatter
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16904; -- stormrage-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19337; -- the-black-book
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19334; -- the-untamed-blade
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16944; -- belt-of-ten-storms
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16925; -- belt-of-transcendence
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16910; -- bloodfang-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19346; -- dragonfang-blade
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16936; -- dragonstalkers-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19372; -- helm-of-endless-rage
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16952; -- judgement-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19339; -- mind-quickening-gem
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16933; -- nemesis-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16818; -- netherwind-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19371; -- pendant-of-the-fallen-dragon
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19348; -- red-dragonscale-protector
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19340; -- rune-of-metamorphosis
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16903; -- stormrage-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16960; -- waistband-of-wrath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19373; -- black-brood-pauldrons
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16906; -- bloodfang-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16919; -- boots-of-transcendence
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19374; -- bracers-of-arcane-accuracy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16941; -- dragonstalkers-greaves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16949; -- greaves-of-ten-storms
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19350; -- heartstriker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16957; -- judgement-sabatons
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19341; -- lifegiving-gem
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19351; -- maladath-runed-blade-of-the-black-flight
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16927; -- nemesis-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16912; -- netherwind-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16965; -- sabatons-of-wrath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16898; -- stormrage-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19342; -- venomous-totem
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19399; -- black-ash-robe
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19365; -- claw-of-the-black-drake
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19398; -- cloak-of-firemaw
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19400; -- firemaws-clutch
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19402; -- legguards-of-the-fallen-crusader
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19344; -- natural-alignment-crystal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19401; -- primalists-linked-legguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19343; -- scrolls-of-blinding-light
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19345; -- aegis-of-preservation
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19403; -- band-of-forced-concentration
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19368; -- dragonbreath-hand-cannon
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19406; -- drake-fang-talisman
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19407; -- ebony-flame-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19405; -- malfurions-blessed-bulwark
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19432; -- circle-of-applied-force
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19367; -- dragons-touch
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19433; -- emberweave-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19357; -- herald-of-woe
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19430; -- shroud-of-pure-thought
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19431; -- styleens-impeding-scarab
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16907; -- bloodfang-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16940; -- dragonstalkers-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19353; -- drake-talon-cleaver
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19394; -- drake-talon-pauldrons
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16948; -- gauntlets-of-ten-storms
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16964; -- gauntlets-of-wrath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16920; -- handguards-of-transcendence
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16956; -- judgement-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16928; -- nemesis-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16913; -- netherwind-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19395; -- rejuvenating-gem
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19397; -- ring-of-blackrock
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19355; -- shadow-wing-focus-staff
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16899; -- stormrage-handguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19396; -- taut-dragonhide-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19388; -- angelistas-grasp
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19361; -- ashjrethul-crossbow-of-smiting
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16832; -- bloodfang-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19387; -- chromatic-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19352; -- chromatically-tempered-sword
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19347; -- claw-of-chromaggus
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16937; -- dragonstalkers-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19349; -- elementium-reinforced-bulwark
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19386; -- elementium-threaded-cloak
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19385; -- empowered-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16945; -- epaulets-of-ten-storms
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19392; -- girdle-of-the-fallen-crusader
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16953; -- judgement-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16932; -- nemesis-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16917; -- netherwind-mantle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16924; -- pauldrons-of-transcendence
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16961; -- pauldrons-of-wrath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19393; -- primalists-linked-waistguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19391; -- shimmering-geta
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16902; -- stormrage-pauldrons
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19390; -- taut-dragonhide-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19389; -- taut-dragonhide-shoulderpads
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19376; -- archimtiros-ring-of-reckoning
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19364; -- ashkandi-greatsword-of-the-brotherhood
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16905; -- bloodfang-chestpiece
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19381; -- boots-of-the-shadow-flame
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16950; -- breastplate-of-ten-storms
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16966; -- breastplate-of-wrath
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19378; -- cloak-of-the-brood-lord
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19363; -- crulshorukh-edge-of-chaos
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16942; -- dragonstalkers-breastplate
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19002; -- head-of-nefarian
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19003; -- head-of-nefarian
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16958; -- judgement-breastplate
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19360; -- lokamir-il-romathis
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19375; -- mishundare-circlet-of-the-mind-flayer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19379; -- neltharions-tear
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16931; -- nemesis-robes
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16916; -- netherwind-robes
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19377; -- prestors-talisman-of-connivery
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19382; -- pure-elementium-band
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16923; -- robes-of-transcendence
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19356; -- staff-of-the-shadow-flame
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 16897; -- stormrage-chestguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19380; -- therazanes-link

-- AQ40 loot weights
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21837; -- anubisath-warhammer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21838; -- garb-of-royal-ascension
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21888; -- gloves-of-the-immortal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21889; -- gloves-of-the-redeemed-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21856; -- neretzek-the-blood-drinker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21836; -- ritssyns-ring-of-chaos
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21891; -- shard-of-the-fallen-star
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20736; -- formula-enchant-cloak-dodge
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20734; -- formula-enchant-cloak-stealth
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20729; -- formula-enchant-gloves-fire-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20728; -- formula-enchant-gloves-frost-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20730; -- formula-enchant-gloves-healing-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20727; -- formula-enchant-gloves-shadow-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20731; -- formula-enchant-gloves-superior-agility
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20929; -- carapace-of-the-old-god
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20933; -- husk-of-the-old-god
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21232; -- imperial-qiraji-armaments
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21237; -- imperial-qiraji-regalia
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20927; -- ouros-intact-hide
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20928; -- qiraji-bindings-of-command
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20932; -- qiraji-bindings-of-dominance
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20931; -- skin-of-the-great-sandworm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20930; -- veklors-diadem
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20926; -- veknilashs-circlet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21218; -- blue-qiraji-resonating-crystal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21323; -- green-qiraji-resonating-crystal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21324; -- yellow-qiraji-resonating-crystal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21321; -- red-qiraji-resonating-crystal
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21702; -- amulet-of-foul-warding
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21699; -- barrage-shoulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21708; -- beetle-scaled-wristguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21705; -- boots-of-the-fallen-prophet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21704; -- boots-of-the-redeemed-prophecy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21706; -- boots-of-the-unwavering-will
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21814; -- breastplate-of-annihilation
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21701; -- cloak-of-concentrated-hatred
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21703; -- hammer-of-jizhi
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21698; -- leggings-of-immersion
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21700; -- pendant-of-the-qiraji-guardian
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22222; -- plans-thick-obsidian-breastplate
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21707; -- ring-of-swarming-thought
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21128; -- staff-of-the-qiraji-prophets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21690; -- angelistas-charm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21695; -- angelistas-touch
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21682; -- bile-covered-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21688; -- boots-of-the-fallen-hero
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21697; -- cape-of-the-trinity
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21689; -- gloves-of-ebru
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21693; -- guise-of-the-devourer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21686; -- mantle-of-phrenic-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21683; -- mantle-of-the-desert-crusade
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21684; -- mantle-of-the-deserts-fury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21691; -- ooze-ridden-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21685; -- petrified-scarab
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21681; -- ring-of-the-devoured
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21696; -- robes-of-the-triumvirate
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21694; -- ternary-mantle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21692; -- triad-girdle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21687; -- ukkos-ring-of-darkness
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21680; -- vest-of-swift-execution
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21603; -- wand-of-qiraji-nobility
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21670; -- badge-of-the-swarmguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21669; -- creeping-vine-helm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21674; -- gauntlets-of-steadfast-determination
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21672; -- gloves-of-enforcement
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21676; -- leggings-of-the-festering-swarm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21667; -- legplates-of-blazing-light
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21678; -- necklace-of-purity
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21648; -- recomposed-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21671; -- robes-of-the-battleguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21666; -- sarturas-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21668; -- scaled-leggings-of-qiraji-fury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21673; -- silithid-claw
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21675; -- thick-qirajihide-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21650; -- ancient-qiraji-ripper
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21635; -- barb-of-the-sand-reaver
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21664; -- barbed-choker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21627; -- cloak-of-untold-secrets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21647; -- fetish-of-the-sand-reaver
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21645; -- hive-tunnelers-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22402; -- libram-of-grace
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21665; -- mantle-of-wicked-revenge
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21639; -- pauldrons-of-the-unrelenting
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21663; -- robes-of-the-guardian-saint
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21651; -- scaled-sand-reaver-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21652; -- silithid-carapace-chestguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22396; -- totem-of-life
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21624; -- gauntlets-of-kalimdor
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21623; -- gauntlets-of-the-righteous-champion
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22399; -- idol-of-health
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20928; -- qiraji-bindings-of-command
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20932; -- qiraji-bindings-of-dominance
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21677; -- ring-of-the-qiraji-fury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21625; -- scarab-brooch
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21622; -- sharpened-silithid-femur
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21626; -- slime-coated-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21621; -- cloak-of-the-golden-hive
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21619; -- gloves-of-the-messiah
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21618; -- hive-defiler-wristguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21616; -- huhurans-stinger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20928; -- qiraji-bindings-of-command
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20932; -- qiraji-bindings-of-dominance
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21620; -- ring-of-the-martyr
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21617; -- wasphide-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21608; -- amulet-of-veknilash
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21606; -- belt-of-the-fallen-emperor
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21600; -- boots-of-epiphany
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21604; -- bracelets-of-royal-redemption
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21605; -- gloves-of-the-hidden-temple
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21607; -- grasp-of-the-fallen-emperor
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21679; -- kalimdors-revenge
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21602; -- qiraji-execution-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21609; -- regenerating-belt-of-veknilash
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21601; -- ring-of-emperor-veklor
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21598; -- royal-qiraji-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21597; -- royal-scepter-of-veklor
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20930; -- veklors-diadem
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21599; -- veklors-gloves-of-devastation
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20926; -- veknilashs-circlet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21611; -- burrower-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21615; -- don-rigobertos-lost-hat
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23570; -- jom-gabbar
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23557; -- larvae-of-the-great-worm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20927; -- ouros-intact-hide
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20931; -- skin-of-the-great-sandworm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23558; -- the-burrowers-shell
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21610; -- wormscale-blocker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21586; -- belt-of-never-ending-agony
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20929; -- carapace-of-the-old-god
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21583; -- cloak-of-clarity
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22731; -- cloak-of-the-devoured
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21134; -- dark-edge-of-insanity
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21585; -- dark-storm-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21126; -- deaths-sting
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21221; -- eye-of-cthun
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22730; -- eyestalk-waist-cord
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21581; -- gauntlets-of-annihilation
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21582; -- grasp-of-the-old-god
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 20933; -- husk-of-the-old-god
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22732; -- mark-of-cthun
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21596; -- ring-of-the-godslayer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21839; -- scepter-of-the-false-prophet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 21579; -- vanquished-tentacle-of-cthun

-- Naxx loot weights
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22726; -- splinter-of-atiesh
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22682; -- frozen-rune
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22369; -- desecrated-bindings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22355; -- desecrated-bracers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22362; -- desecrated-wristguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22357; -- desecrated-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22371; -- desecrated-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22364; -- desecrated-handguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22370; -- desecrated-belt
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22363; -- desecrated-girdle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22356; -- desecrated-waistguard
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22366; -- desecrated-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22359; -- desecrated-legguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22352; -- desecrated-legplates
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22365; -- desecrated-boots
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22358; -- desecrated-sabatons
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22372; -- desecrated-sandals
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22349; -- desecrated-breastplate
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22351; -- desecrated-robe
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22350; -- desecrated-tunic
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22354; -- desecrated-pauldrons
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22368; -- desecrated-shoulderpads
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22361; -- desecrated-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22367; -- desecrated-circlet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22360; -- desecrated-headpiece
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22353; -- desecrated-helmet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23060; -- bonescythe-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23062; -- frostfire-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23063; -- plagueheart-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23061; -- ring-of-faith
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23066; -- ring-of-redemption
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23067; -- ring-of-the-cryptstalker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23059; -- ring-of-the-dreadnaught
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23064; -- ring-of-the-dreamwalker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23065; -- ring-of-the-earthshatterer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23666; -- belt-of-the-grand-crusader
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23226; -- ghoul-skin-tunic
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23663; -- girdle-of-elemental-fury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23044; -- harbinger-of-doom
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23665; -- leggings-of-elemental-fury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23668; -- leggings-of-the-grand-crusader
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23221; -- misplaced-servo-arm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23069; -- necro-knights-garb
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23664; -- pauldrons-of-elemental-fury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23237; -- ring-of-the-eternal-flame
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23667; -- spaulders-of-the-grand-crusader
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23238; -- stygian-buckler
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22374; -- wartorn-chain-scrap
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22376; -- wartorn-cloth-scrap
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22373; -- wartorn-leather-scrap
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22375; -- wartorn-plate-scrap
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22939; -- band-of-unanswered-prayers
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22938; -- cryptfiend-silk-cloak
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22937; -- gem-of-nerubis
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22935; -- touch-of-frost
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22936; -- wristguards-of-vengeance
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22940; -- icebane-pauldrons
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22943; -- malice-stone-pendant
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22941; -- polar-shoulder-pads
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22942; -- the-widows-embrace
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22806; -- widows-remorse
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23220; -- crystal-webbed-robe
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22357; -- desecrated-gauntlets
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22371; -- desecrated-gloves
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22364; -- desecrated-handguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22954; -- kiss-of-the-spider
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22804; -- maexxnas-fang
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22947; -- pendant-of-forgotten-names
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22807; -- wraith-blade
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23031; -- band-of-the-inevitable
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23030; -- cloak-of-the-scourge
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23028; -- hailstone-band
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22816; -- hatchet-of-sundered-bone
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23006; -- libram-of-light
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23029; -- noths-frigid-heart
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23005; -- totem-of-flowing-water
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23019; -- icebane-helmet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23033; -- icy-scale-coif
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23068; -- legplates-of-carnage
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23036; -- necklace-of-necropsy
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23035; -- preceptors-hat
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23038; -- band-of-unnatural-forces
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22800; -- brimstone-staff
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22366; -- desecrated-leggings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22359; -- desecrated-legguards
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22352; -- desecrated-legplates
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23042; -- loathebs-reflection
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23037; -- ring-of-spiritual-fervor
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23039; -- the-eye-of-nerub
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23219; -- girdle-of-the-mentor
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23014; -- iblis-blade-of-the-fallen-seraph
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23004; -- idol-of-longevity
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23018; -- signet-of-the-fallen-defender
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23017; -- veil-of-eclipse
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23009; -- wand-of-the-whispering-dead
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23073; -- boots-of-displacement
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23032; -- glacial-headdress
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23020; -- polar-helmet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23023; -- sadists-collar
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23021; -- the-soul-harvesters-bindings
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22691; -- corrupted-ashbringer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22349; -- desecrated-breastplate
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22351; -- desecrated-robe
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22350; -- desecrated-tunic
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23071; -- leggings-of-apocalypse
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22809; -- maul-of-the-redeemed-crusader
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23025; -- seal-of-the-damned
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22811; -- soulstring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23027; -- warmth-of-forgiveness
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22961; -- band-of-reanimation
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22960; -- cloak-of-suturing
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22815; -- severance
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22818; -- the-plague-bearer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22820; -- wand-of-fates
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22968; -- glacial-mantle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22967; -- icy-scale-spaulders
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22803; -- midnight-haze
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22988; -- the-end-of-dreams
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22810; -- toxin-injector
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22813; -- claymore-of-unholy-might
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23075; -- deaths-bargain
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22994; -- digested-hand-of-power
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22981; -- gluths-missing-collar
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22983; -- rime-covered-mantle
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22367; -- desecrated-circlet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22360; -- desecrated-headpiece
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22353; -- desecrated-helmet
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23001; -- eye-of-diminution
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23070; -- leggings-of-polarity
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23000; -- plated-abomination-ribcage
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22801; -- spire-of-twilight
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22808; -- the-castigator
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23242; -- claw-of-the-frost-wyrm
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23050; -- cloak-of-the-necropolis
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23047; -- eye-of-the-dead
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23549; -- fortitude-of-the-scourge *
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23040; -- glyph-of-deflection
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23548; -- might-of-the-scourge
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23545; -- power-of-the-scourge
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23547; -- resilience-of-the-scourge *
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23049; -- sapphirons-left-eye
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23048; -- sapphirons-right-eye
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23045; -- shroud-of-dominion
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23041; -- slayers-crest
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23043; -- the-face-of-death
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23046; -- the-restrained-essence-of-sapphiron
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23060; -- bonescythe-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22821; -- doomfinger
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23062; -- frostfire-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23057; -- gem-of-trapped-innocents
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23054; -- gressil-dawn-of-ruin
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23056; -- hammer-of-the-twisting-nether
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22802; -- kingsfall
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22798; -- might-of-menethil
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22812; -- nerubian-slavemaker *
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23063; -- plagueheart-ring
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23061; -- ring-of-faith
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23066; -- ring-of-redemption
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23067; -- ring-of-the-cryptstalker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23059; -- ring-of-the-dreadnaught
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23064; -- ring-of-the-dreamwalker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23065; -- ring-of-the-earthshatterer
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22819; -- shield-of-condemnation
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22799; -- soulseeker
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23053; -- stormrages-talisman-of-seething
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 23577; -- the-hungering-cold *
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22520; -- the-phylactery-of-kelthuzad

-- Legendaries
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 17182; -- Hand of Ragnaros
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 19019; -- Thunderfury
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22589; -- Atiesh, Greatstaff of the Guardian (mage)
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22631; -- Atiesh, Greatstaff of the Guardian (priest)
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22632; -- Atiesh, Greatstaff of the Guardian (druid)
UPDATE `items` SET `weight` = 0.5 WHERE `item_id` = 22630; -- Atiesh, Greatstaff of the Guardian (warlock)
